"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  Anchor,
  ColorSchemeScript,
  Container,
  Group,
  mantineHtmlProps,
  MantineProvider,
  Space,
  Text,
} from "@mantine/core";

// Using layered imports here to be able to override Mantine's CSS, see
// https://mantine.dev/styles/mantine-styles/#css-layers.
import "@mantine/core/styles.layer.css";
import "@mantine/code-highlight/styles.layer.css";
import "./globals.css";
import { Header } from "@/components/Header";
import { theme } from "@/theme";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps} className={interFont.variable}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Header />
          {children}
          <Space h={50} />
          <footer style={{ backgroundColor: "var(--mantine-color-gray-0)" }}>
            <Container size="lg" p="xl">
              <Group h={100}>
                <Text c="dimmed" fz="sm">
                  &copy; Prometheus Authors 2014-2024 | Documentation
                  Distributed under CC-BY-4.0
                </Text>
                <Text c="dimmed" fz="sm">
                  &copy; 2024 The Linux Foundation. All rights reserved. The
                  Linux Foundation has registered trademarks and uses
                  trademarks. For a list of trademarks of The Linux Foundation,
                  please see our{" "}
                  <Anchor
                    inherit
                    href="https://www.linuxfoundation.org/trademark-usage"
                    target="_blank"
                  >
                    Trademark Usage
                  </Anchor>{" "}
                  page.
                </Text>
              </Group>
            </Container>
          </footer>
        </MantineProvider>
      </body>
    </html>
  );
}
